use aircraftSimulationDB;

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'aircraftSimulationDB'
  AND TABLE_NAME = 'test'
  AND COLUMN_KEY = 'PRI';
  
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
	REFERENCED_TABLE_SCHEMA = 'aircraftSimulationDB'
    AND REFERENCED_TABLE_NAME = 'test';